---
brew_taps:
  - heroku/brew
  # Note: homebrew/bundle and homebrew/services are now part of core Homebrew
  # Note: microsoft/git is no longer needed; git is available from core Homebrew

brew_packages:
  # --- Core System Tools ---
  - bash
  - zsh
  - coreutils
  - diffutils
  - gzip
  - less
  - nano
  - openssh
  - rsync
  - wget
  - tree

  # --- Version Managers ---
  - nvm
  - pyenv
  - rbenv
  - ruby-build
  - # Don't install ruby from homebrew; use rbenv for this

  # --- Python Tools & Package Management ---
  - pipx
  - uv # modern Python package manager
  - pre-commit
  - python@3.14

  # --- Build Tools & Compilers ---
  - autoconf
  - automake
  - binutils
  - cmake

  # --- Ruby Dependencies ---
  - gmp # rbenv/ruby requirement
  - libffi
  - libyaml # rbenv/ruby requirement
  - openssl@3 # rbenv/ruby requirement
  - readline # rbenv/ruby requirement
  - zlib

  # --- Development Tools ---
  - ansible
  - ansible-lint
  - docker
  - duti
  - exiftool
  - git
  - gnupg
  - shellcheck
  - stripe/stripe-cli/stripe
  - yamllint
  - yq

  # --- Cloud & Infrastructure CLIs ---
  - awscli
  - hcloud
  - heroku/brew/heroku
  - upcloud-cli

  # --- Database & Network Tools ---
  - jq # JSON processor
  - libpq # postgres requirement
  - nmap
  - unbound

  # --- System Utilities ---
  - duf # disk usage
  - htop # system monitor
  - mas # Mac App Store CLI
  - tidy-html5
  - wifi-password

brew_cask_packages:
  # --- Development & Coding ---
  - github
  - iterm2
  - sublime-text
  - visual-studio-code

  # --- Browsers & Web ---
  - chromedriver
  - firefox
  - google-chrome
  - ngrok

  # --- Communication & Collaboration ---
  - element
  - microsoft-teams
  - signal
  - skype
  - slack
  - thunderbird

  # --- Cloud & Infrastructure ---
  - docker
  - microsoft-remote-desktop

  # --- Productivity & Office ---
  - google-drive
  - microsoft-auto-update
  - microsoft-office
  - obsidian
  - omnifocus
  - scrivener
  - timing

  # --- Media & Entertainment ---
  - keka # open source alternative to the unarchiver
  - kindle
  - simple-comic
  - spotify
  - transmission
  - vlc

  # --- Utilities & Tools ---
  - 1password
  - arq # backup
  - authy
  - cyberduck
  - dupeguru
  - exiftool
  - fujitsu-scansnap-home
  - git-credential-manager
  - hazel
  - little-snitch
  - maccy
  - macfuse
  - maestral
  - netnewswire
  - superduper
  - tabula
  - teamviewer
  - the-unarchiver
  - utm
  - veracrypt
  - zoom

brew_cask_ql_packages:
  - qlcolorcode
  - qlimagesize
  - qlmarkdown
  - qlprettypatch
  - qlstephen
  - qlvideo
  - quicklook-csv
  - quicklook-json
  - suspicious-package
  - webpquicklook
